### ISSUE TITLE
Missing instructions for set to run sync_gui.py directly

### ISSUE THREAD

**Issue by rkent** [operepo/ope#10]
In addressing any issues in SyncApp, you need to run the local python code in admin_app/sync_gui.py  But by default that does not have the required python modules installed. I THINK I got it working correctly on my system with various pip installs, but I am not sure I am using the canonical methods. Maybe my Python foo is weak and there is an obvious way to install these, but otherwise it would be good to have a list of required installs for the python version.

**Comment by frankyrumple** [comment]
Pip install is the correct way. Considering setting up a python virtual env and checking in with code. Not sure if that is considered good or bad.

Started a modules.txt file in admin_app folder. List is likely not complete yet, so not closing.

**Comment by frankyrumple** [comment]
modules.txt file should have list of required modules. Closing issue.
