### ISSUE TITLE
build_config uses stable_apps instead of beta_apps

### ISSUE THREAD

**Issue by rkent** [operepo/ope#11]
In this code (sync_gui.py near line 450):
```
        # stable apps
        for item in SyncOPEApp.stable_apps:
            selected_apps[item] = '0'
        # beta apps
        for item in SyncOPEApp.stable_apps:
            selected_apps[item] = '0'
```
after #beta apps it should be:
```
        # beta apps
        for item in SyncOPEApp.beta_apps:
```
I'm not really sure where build_config is called, it must be deep in the assumptions of kivy or ConfigParser. That would be worth a comment in the code for those of us less steeped in kivy.

**Comment by frankyrumple** [comment]
Good catch. Fixed.
