### ISSUE TITLE
Problems running latest release (pulled 2018-01-29)

### ISSUE THREAD

**Issue by rkent** [operepo/ope#12]
I updated ope on a flashdrive connected to my Windows machine to the latest operepo/ope version (actually did a fresh git clone). Problems encountered:

## Running SyncApp/SyncApp.exe on the flashdrive:
```
  SYNC ERROR - Unable to complete sync
```
On command line, last lines were:
```
From https://github.com/operepo/ope_server_sync_binaries
* [new branch]      master     -> master
* [new branch]      master     -> ope_origin/master
No handlers could be found for logger "paramiko.transport"
```
Possible Solutions? See https://stackoverflow.com/questions/19152578/no-handlers-could-be-found-for-logger-paramiko which suggests either
Basically, you just need to add a line:
```
paramiko.util.log_to_file("filename.log")
```
or
please add the code in your script
```
logging.raiseExceptions=False
```
Alternative solution from https://stackoverflow.com/questions/40293097/compiled-python-script-no-handlers-could-be-found-for-logger-paramiko-transpor?noredirect=1&lq=1
```
import logging
paramiko_logger = logging.getLogger('paramiko.transport')
if not paramiko_logger.handlers:
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(
        logging.Formatter('%(asctime)s | %(levelname)-8s| PARAMIKO: '
                      '%(lineno)03d@%(module)-10s| %(message)s')
    )
paramiko_logger.addHandler(console_handler)
```
With the exec-ified SyncApp.exe I don't know how to address issues like this, so I tried to switch to the locally run python version.

### Missing modules
I've previously run this before using my local python setup (with global libraries) but this time I got two new missing modules paramiko and pyaes. I solved these by running:
```
pip install paramiko
pip install pyaes
```
both of which seemed to install successfully, and allowed my to run sync_gui.py
### First run: git failure
With these changes, I got further with sync_gui (in particular, the online remote /ope folder now has content in ./volumes and ./smc) but then I got this failure (seen from the command line):
```
Pushing ope_server_sync_binaries
-- Init
-- Remove Remote
-- Add Remote
-- Push
Counting objects: 6716, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4815/4815), done.
Writing objects: 100% (6716/6716), 135.70 MiB | 37.94 MiB/s, done.
Total 6716 (delta 1508), reused 6716 (delta 1508)
remote: Resolving deltas: 100% (1508/1508), done.
To ssh://192.168.0.182:/ope/volumes/smc/git/ope_server_sync_binaries.git
 * [new branch]      master -> master
---- fatal: Not a git repository (or any of the parent directories): .git
```
(Note the only optional server that I selected is ope-fog)
Running the app a second time, I did not see this error, so it looks like a first-run glitch. I'll try to duplicate that in a few minutes.

### Second run: 
Successfully went to completion, though docker ps only shows ope-router and ope-dns running. But that might be because I had another docker app running.

OPE Admin tool only shows the error: 'No secret file!' (which makes sense, I did not set that up). Command line shows nothing that looks like an error.

At this point, I was able to go to the docker linux server, run rebuild_compose.py, then docker-compose down and docker-compose up, and everything I expect seems to be running.

(Running in a non-AD environment, I add servers to my windows host file to point to the IP address of the docker server. In particular I added fog.ed)

Now I can http://fog.ed and I get the FOG login screen!

**Comment by frankyrumple** [comment]
Added logging code under import paramiko, also started modules.txt to list needed python modules.

**Comment by frankyrumple** [comment]
Should be fixed, needs testing and binary build to confirm.

**Comment by frankyrumple** [comment]
Believe this is fixed. No further reports since feb 18.
