### ISSUE TITLE
Automatic builds on Docker Hub

### ISSUE THREAD

**Issue by alexanderadam** [operepo/ope#29]
Thank you for your work! :pray: 

It would be great if you could use [GitHub Actions](https://help.github.com/en/actions/building-actions/creating-a-docker-container-action) or any other service for automatic image builds on Docker Hub.

I just saw that the CodeCombat image was updated 3 years ago although [CodeCombat is getting updates every few days](https://github.com/codecombat/codecombat/commits/master).

**Comment by frankyrumple** [comment]
Thanks for your suggestion, it sounds like a great idea. I am setting this as an enhancement to do in the future when workload permits...
