### ISSUE TITLE
Pull from operepo/ope.git is unexpected when developing with SyncApp

### ISSUE THREAD

**Issue by rkent** [operepo/ope#3]
When running the SyncApp, started from a local version of ope, one of the steps (sync_gui.py git_pull_local) does a pull in the current project folder from https://github.com/operepo/ope.git branch master. That is surprising behavior, normally I would assume that I have complete control of my local /ope directory, and I would not expect a sync app to be messing with it.

I guess I'm not really sure of the use case for SyncApp. But if I am trying to use it to test, I really don't want it messing with my ope folder. I suppose you are trying to make this "fool proof" for someone who is not that familiar with git, but I assume that most users would be tech professionals who should be able to handle git.

**Comment by frankyrumple** [comment]
I agree - if you are doing dev work in the /ope folder and running the syncapp it gets muddy. It would be good to have a clear boundary between production and dev work.

Would recommending dev work be done in a separate folder (e.g. /opedev ) be adequate?

For production work - it is assumed that IT personnel don't have experience with the Linux command line and therefore they wouldn't run commands themselves.

**Comment by rkent** [comment]
In the short run, a simple approach I was hoping to look at would be to add some environment variables that could be set during development, that would use the existing values in the repo instead of trying to update. BTW the same issue exists for pulls from npm where you are updating packages that are also defined locally. I've only recently managed to setup what I hope is a viable working environment to do development on ope again, and I was hoping to propose some simple changes along these lines to allow development and testing by setting environment variables.

In the longer run, I think that it is problematic to have one program in the application be pulling from an external source to override git-managed local code in the same repository. I'm not exactly sure what you mean by an /opedev folder here though. Right now, the updates are being done in the folder that you are running from. Perhaps what you are proposing is that instead, there is one folder with the code, and a separate one that contains the code that is updated, with a structure like this:

```
/myopeprojectfolder
  /ope
  /opedev
```
in which the code in /opedev would pull into /ope? I'm not sure how that would work. I think it would be more typical to have something like this:

```
/myopeprojectfolder
  /ope
    /ope-build
```

in which case /ope-build is a .gitignored'd folder that is the working directory during use, and that you could update if you wanted (though I still think automatic update while running is an unexpected behavior) but you would not touch the code in /ope while running SyncApp. In any case, I don't see how SyncApp can be pulling update code that could also include changes to SyncApp itself while it is running.

I'm going to have to think a little more about possible approaches to this in the long run.

**Comment by frankyrumple** [comment]
Exactly what I mean about it getting muddy. It isn't clear when we are using Git as an app update, and when we are using it as code tracking.
The alternate folder (e.g. opedev) is one way to make a clearer split.
What if the syncapp does a git status and won't run git commands if there are changes? Pops up a warning? Does stash save and shows a warning on how to get your changes back?

**Comment by frankyrumple** [comment]
What if we add a .dev file in the /ope folder, and if that exists the syncapp won't do the git pull commands?
