### ISSUE TITLE
SyncApp fails with missing operepo/... docker hub image

### ISSUE THREAD

**Issue by rkent** [operepo/ope#4]
Starting from a case where, on the Docker server, the /ope folder is missing, SyncApp creates and updates the /ope folder, but then tries to download selected images from dockerhub operepo/... locations. Most of these do not exist (in particular, ope-jsbin) so the sync run fails.

Information exists to build these locally. It seems odd to me that we copy all of the Dockerfile stuff to the Docker server, but then do not really use that, instead using the online version from Docker hub.

Workaround: from /ope/docker_build_files, run
```
./up.sh b
```

**Comment by frankyrumple** [comment]
Beta docker apps may not have been pushed to dockerhub yet. It would be a good idea to push a dummy app like alpine just so this doesn't fail.

We need the docker_build_files folders to rebuild the docker-compse.yml file that docker uses. 

We can look at separating the docker_build_files and needed folders from the rest of the code. As we get stable I will look at splitting things further.

**Comment by jmichel-sbctc** [comment]
Closing this issue. If I'm correct this is no longer an issue with the current build and hasn't been for a few releases.
