### ISSUE TITLE
get_app_folder returns wrong folder if cwd has been done

### ISSUE THREAD

**Issue by rkent** [operepo/ope#6]
Trying to run SyncApp locally (that is in admin_app run "python sync_gui.py") I get a missing file failure trying to do an online sync. Traced this to failure to get the path for PortableGIt. In get_app_folder, this code:

os.path.dirname(os.path.abspath(__file__))

is dependent on the current value of the working directory, as __file__ is simply "sync_gui.py". Something has changed the working directory (confirmed by local logging of os.getcwd()) so get_app_folder is returning the parent of the ope folder, not the ope folder as desired. Occurs in update_online_server_worker/generate_local_ssh_key

(I assume here we are running Python 2.7  In Python 3.4 IIUC __file__ is always an absolute reference)

**Comment by frankyrumple** [comment]
Changed to save app_folder into a global variable, then returns it later instead of recalculating each call. Function called during app startup to make sure it is saved early.
