### ISSUE TITLE
When unzipping new version of "ope_laptop_binaries" Windows security reportd CryptInject!ml trojan in file.

### ISSUE THREAD

**Issue by FosterNostrand** [operepo/ope#65]
I don't know if this is a false positive or not.

When I was unzipping ope_laptop_binaries on my desktop I got an alert from Windows Security that is detailed below. It did not allow mgmt.exe to be unzipped and I did not continue trying.
 
Below is the warning I recieved:

Trojan:Win32/CryptInject!ml

Alert level: Severe
Status: Active
Date: 12/13/2020 3:53 PM
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Affected items:
file: F:\ope_laptop_binaries-master\ope_laptop_binaries-master\Services\mgmt\mgmt.exe

**Comment by frankyrumple** [comment]
Pyinstaller generated apps started tripping windows defender antivirus as a false positive. Updated to more recent pyinstaller to solve this.
