### ISSUE TITLE
Canvas 'read only'?

### ISSUE THREAD

**Issue by Jason-Davison-SCCC** [operepo/ope#78]
I have run into this issue twice now; once with a power outage and again today as we brought the servers back online from Campus to Stafford. Canvas started normally but eventually wouldn't take a laptops sync - a read error was listed for each assignment that was attempted to be uploaded. I looked at the Canvas course and it looked and functioned normally until I tried to add a new assignment to try and sync to. It wouldn't add anything to Canvas - no changed took place. Rebooting the system using the OPE Admin Tool made it work, but it happened twice now and apparently after being recently boot back up.

**Comment by jmichel-sbctc** [comment]
Issue hasn't seemed to return. Closing the issue but will keep an eye out for the issue coming back.
