### ISSUE TITLE
Laptop LMS wont take a submission/copy

### ISSUE THREAD

**Issue by Jason-Davison-SCCC** [operepo/ope#81]
I have one laptop that will not allow a file to be dragged over to the File Upload area. I drag it and it looks like it gets copied, but syncing doesn't move the file to Canvas. When I check under Submissions tab, it still shows as blank. 

Sidenote - there are 2 users for the student now. One that is the standard, and another that is standard but with a OPE_LT_1 behind it. Permissions may be off?

**Comment by Jason-Davison-SCCC** [comment]
I seemed to have luck using the older default image and profile/sync success. I was using the GED Academy image before and removing programs as needed for non-GED students. Maybe something in the image was just different enough to cause this bug. Still playing with it.

**Comment by jmichel-sbctc** [comment]
The bug is identified in issue #87.

Closing this issue as it is being tracked on issue #87.
