### ISSUE TITLE
Initial sync to Linux server fails because ssh key is not accepted

### ISSUE THREAD

**Issue by rkent** [operepo/ope#9]
With a new Linux server, I went through normal SyncApp setup to sync. That failed with a message about problems with ssh (Sorry, did not write down the full message).

I logged in instead using Putty, found that the IP address had an incorrect server key. I allowed it in Putty, after that SyncApp worked normally.

**Comment by frankyrumple** [comment]
Sounds like an issue with the ~/.ssh/known_hosts file. That would happen if there was an existing ip/key combo then you build a new VM and use the same IP.

I added exception code to give a clearer error in this case. 

Also recently added look_for_keys=False to the connect parameter. Not sure if this will effect this or not.

**Comment by frankyrumple** [comment]
Adjustments to look_for_keys=False forces ssh connection with pw.
