### ISSUE TITLE
Credential closing after putting in KMS address

### ISSUE THREAD

**Issue by mdhuse** [operepo/ope#93]
When I am putting in the default KMS address or accept the default the credential window just closes. If I choose not to put in KMS address the credential process continues as normal.

**Comment by mdhuse** [comment]
Update - When trying to set date/time clicking "N" for the time is correct the option to set date/time is not there. It just continues on with the credential process.

**Comment by mdhuse** [comment]
Opps clicked Close with comment.

**Comment by mdhuse** [comment]
Here is the code to fix the issue. Just need to replace the code in the CredentialLaptop.cmd where the line "rem Contributions from Mike Huse https://...."
[Time-Date-KMS-Fixed.txt](https://github.com/operepo/ope/files/7269623/Time-Date-KMS-Fixed.txt)

**Comment by frankyrumple** [comment]
Thanks Mike!
Copied in. Will come out with mgmt release 1.0.109

**Comment by mdhuse** [comment]
Update in 1.0.109 fixed issue. Thanks Ray!!
