### ISSUE TITLE
Very/Frozen slow gpupate/force when running mgmt unlock_machine

### ISSUE THREAD

**Issue by frankyrumple** [operepo/ope#94]
Very/Frozen slow gpupate/force when running mgmt unlock_machine

At times, during the credential, when running unlock machine the credential app will freeze or be very very slow, requiring tech action to close and re-run the credential multiple times.

The "Freeze" is happening in the gpupdate utility - unknown what is causing it to stick.

Possible Solution:
Added code to mgmt to unlock machine - will check if any group policy rules exist - if not, then will skip the reset step. Hopefully this will help eliminate the "freeze" during credential.

Should be released with mgmt version 1.0.109

**Comment by jmichel-sbctc** [comment]
This issue should be resolved in the most recent version of the ope laptop binaries. Version: 1.0.117

Tested several times without issue and haven't heard reports of GP hanging up still.
