### ISSUE TITLE
LMS assignments fail to open with Special character in name

### ISSUE THREAD

**Issue by tgoggans** [operepo/ope#95]
A canvas assignment pulled through LMS sync will fail to open if it contains an unsupported character in the file name. Assignment containing a # would not open from LMS but was present in cache and could open directly. Renamed assignment to remove # and it worked fine.

**Comment by jmichel-sbctc** [comment]
Content moved to issue #75 issue is the same and this will keep the progress tracking in one place.

Thank you for the additional information tgoggans.
